<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250329201924 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create table pessoa';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pessoa (
            pes_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            pes_nome VARCHAR(200) NOT NULL,
            pes_data_nascimento DATE NOT NULL,
            pes_sexo VARCHAR(9) NOT NULL,
            pes_mae VARCHAR(200) DEFAULT NULL,
            pes_pai VARCHAR(200) DEFAULT NULL,
            PRIMARY KEY(pes_id)
        )');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE pessoa');
    }
}
