<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250329213153 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Criar entidade de endereços com seus relacionamentos.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            'CREATE TABLE endereco (
                end_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                end_tipo_logradouro VARCHAR(50) NOT NULL,
                end_logradouro VARCHAR(200) NOT NULL,
                end_numero INT NOT NULL,
                end_bairro VARCHAR(100) NOT NULL,
                cid_id INT DEFAULT NULL,
                PRIMARY KEY(end_id)
            )'
        );

        $this->addSql('CREATE INDEX IDX_F8E0D60E86C4B51D ON endereco (cid_id)');
        $this->addSql('CREATE TABLE pessoa_endereco (pes_id INT NOT NULL, end_id INT NOT NULL, PRIMARY KEY(pes_id, end_id))');
        $this->addSql('CREATE INDEX IDX_403BF131BB8470F ON pessoa_endereco (pes_id)');
        $this->addSql('CREATE INDEX IDX_403BF131E2BD8A10 ON pessoa_endereco (end_id)');
        $this->addSql(
            'ALTER TABLE endereco
                ADD CONSTRAINT FK_F8E0D60E86C4B51D
                FOREIGN KEY (cid_id)
                REFERENCES cidade (cid_id)
                NOT DEFERRABLE INITIALLY IMMEDIATE
            '
        );
        $this->addSql(
            'ALTER TABLE pessoa_endereco
                ADD CONSTRAINT FK_403BF131BB8470F
                FOREIGN KEY (pes_id)
                REFERENCES pessoa (pes_id)
                NOT DEFERRABLE INITIALLY IMMEDIATE
            '
        );

        $this->addSql(
            'ALTER TABLE pessoa_endereco
                ADD CONSTRAINT FK_403BF131E2BD8A10
                FOREIGN KEY (end_id)
                REFERENCES endereco (end_id)
                ON DELETE CASCADE
                NOT DEFERRABLE INITIALLY IMMEDIATE
            '
        );
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE endereco DROP CONSTRAINT FK_F8E0D60E86C4B51D');
        $this->addSql('ALTER TABLE pessoa_endereco DROP CONSTRAINT FK_403BF131BB8470F');
        $this->addSql('ALTER TABLE pessoa_endereco DROP CONSTRAINT FK_403BF131E2BD8A10');
        $this->addSql('DROP TABLE endereco');
        $this->addSql('DROP TABLE pessoa_endereco');
    }
}
