<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250329205949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Criar tabelas de cidade e unidade';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            'CREATE TABLE cidade (
                cid_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                cid_nome VARCHAR(200) NOT NULL,
                cid_uf VARCHAR(2) NOT NULL,
                PRIMARY KEY(cid_id)
            )'
        );

        $this->addSql(
            'CREATE TABLE unidade (
                unid_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                unid_nome VARCHAR(200) NOT NULL,
                unid_sigla VARCHAR(20) NOT NULL,
                PRIMARY KEY(unid_id)
            )'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cidade');
        $this->addSql('DROP TABLE unidade');
    }
}
