<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250329211533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Criar tabela de lotação e seus relacionamentos';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE lotacao (
                lot_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                lot_data_lotacao DATE NOT NULL,
                lot_data_remocao DATE DEFAULT NULL,
                lot_portaria VARCHAR(100) NOT NULL,
                pes_id INT DEFAULT NULL,
                unid_id INT DEFAULT NULL,
                PRIMARY KEY(lot_id)
            )'
        );

        $this->addSql('CREATE INDEX IDX_4C6AC15FBB8470F ON lotacao (pes_id)');
        $this->addSql('CREATE INDEX IDX_4C6AC15FA8A42792 ON lotacao (unid_id)');
        $this->addSql(
            'ALTER TABLE lotacao
                ADD CONSTRAINT FK_4C6AC15FBB8470F
                FOREIGN KEY (pes_id)
                REFERENCES pessoa (pes_id)
                NOT DEFERRABLE INITIALLY IMMEDIATE
            '
        );
        $this->addSql(
            'ALTER TABLE lotacao
                ADD CONSTRAINT FK_4C6AC15FA8A42792
                FOREIGN KEY (unid_id)
                REFERENCES unidade (unid_id)
                NOT DEFERRABLE INITIALLY IMMEDIATE
            '
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE lotacao DROP CONSTRAINT FK_4C6AC15FBB8470F');
        $this->addSql('ALTER TABLE lotacao DROP CONSTRAINT FK_4C6AC15FA8A42792');
        $this->addSql('DROP TABLE lotacao');
    }
}
