<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250329202717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Tabela de fotos com referência a pessoa';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE foto_pessoa (
            fp_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            fp_data DATE NOT NULL,
            fp_bucket VARCHAR(50) NOT NULL,
            fp_hash VARCHAR(50) NOT NULL,
            pes_id INT DEFAULT NULL,
            PRIMARY KEY(fp_id)
        )');

        $this->addSql('CREATE INDEX IDX_2F0E01DBBB8470F ON foto_pessoa (pes_id)');
        $this->addSql('ALTER TABLE foto_pessoa
            ADD CONSTRAINT FK_2F0E01DBBB8470F
            FOREIGN KEY (pes_id)
            REFERENCES pessoa (pes_id) NOT DEFERRABLE INITIALLY IMMEDIATE
        ');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE foto_pessoa DROP CONSTRAINT FK_2F0E01DBBB8470F');
        $this->addSql('DROP TABLE foto_pessoa');
    }
}
